const REQUESTING_MOVIE_VIDEOS = 'REQUESTING_MOVIE_VIDEOS'
const REQUEST_MOVIE_VIDEOS_FAILURE = 'REQUEST_MOVIE_VIDEOS_FAILURE'
const REQUEST_MOVIE_VIDEOS_SUCCESS = 'REQUEST_MOVIE_VIDEOS_SUCCESS'

export default {
  REQUESTING_MOVIE_VIDEOS,
  REQUEST_MOVIE_VIDEOS_SUCCESS,
  REQUEST_MOVIE_VIDEOS_FAILURE,
}
