// @action constants/types
export const REQUESTING_MOVIES = 'REQUESTING_MOVIES'
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_FAILURE = 'REQUEST_MOVIES_FAILURE'

export const REQUESTING_MOVIE = 'REQUESTING_MOVIE'
export const REQUEST_MOVIE_SUCCESS = 'REQUEST_MOVIE_SUCCESS'
export const REQUEST_MOVIE_FAILURE = 'REQUEST_MOVIE_FAILURE'
