// @action types
const REQUEST_CONFIGURATION = 'REQUEST_CONFIGURATION'
const REQUEST_CONFIGURATION_SUCCESS = 'REQUEST_CONFIGURATION_SUCCESS'
const REQUEST_CONFIGURATION_FAILURE = 'REQUEST_CONFIGURATION_FAILURE'

export default {
  REQUEST_CONFIGURATION,
  REQUEST_CONFIGURATION_SUCCESS,
  REQUEST_CONFIGURATION_FAILURE,
}
